name: Testing on Ubuntu

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt install -y perl cpanminus
        sudo cpanm --installdeps .
    - name: Verify the basic usage
      run: |
        perl zarn.pl --source . --sarif zarn.sarif
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: zarn.sarif